/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MIndexRouteImport } from './routes/m/index'
import { Route as MSlugRouteImport } from './routes/m/$slug'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminSettingsIndexRouteImport } from './routes/_admin/settings/index'
import { Route as AdminMemorialsIndexRouteImport } from './routes/_admin/memorials/index'
import { Route as AdminContactsIndexRouteImport } from './routes/_admin/contacts/index'
import { Route as MSlugClaimRouteImport } from './routes/m/$slug/claim'
import { Route as AdminSettingsNotificationsRouteImport } from './routes/_admin/settings/notifications'
import { Route as AdminSettingsCustomFieldsRouteImport } from './routes/_admin/settings/custom-fields'
import { Route as AdminMemorialsNewRouteImport } from './routes/_admin/memorials/new'
import { Route as AdminMemorialsCategoriesRouteImport } from './routes/_admin/memorials/categories'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MIndexRoute = MIndexRouteImport.update({
  id: '/m/',
  path: '/m/',
  getParentRoute: () => rootRouteImport,
} as any)
const MSlugRoute = MSlugRouteImport.update({
  id: '/m/$slug',
  path: '/m/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMemorialsIndexRoute = AdminMemorialsIndexRouteImport.update({
  id: '/memorials/',
  path: '/memorials/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactsIndexRoute = AdminContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => AdminRoute,
} as any)
const MSlugClaimRoute = MSlugClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => MSlugRoute,
} as any)
const AdminSettingsNotificationsRoute =
  AdminSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSettingsCustomFieldsRoute =
  AdminSettingsCustomFieldsRouteImport.update({
    id: '/settings/custom-fields',
    path: '/settings/custom-fields',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminMemorialsNewRoute = AdminMemorialsNewRouteImport.update({
  id: '/memorials/new',
  path: '/memorials/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMemorialsCategoriesRoute =
  AdminMemorialsCategoriesRouteImport.update({
    id: '/memorials/categories',
    path: '/memorials/categories',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AdminDashboardRoute
  '/m/$slug': typeof MSlugRouteWithChildren
  '/m/': typeof MIndexRoute
  '/memorials/categories': typeof AdminMemorialsCategoriesRoute
  '/memorials/new': typeof AdminMemorialsNewRoute
  '/settings/custom-fields': typeof AdminSettingsCustomFieldsRoute
  '/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/m/$slug/claim': typeof MSlugClaimRoute
  '/contacts/': typeof AdminContactsIndexRoute
  '/memorials/': typeof AdminMemorialsIndexRoute
  '/settings/': typeof AdminSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AdminDashboardRoute
  '/m/$slug': typeof MSlugRouteWithChildren
  '/m': typeof MIndexRoute
  '/memorials/categories': typeof AdminMemorialsCategoriesRoute
  '/memorials/new': typeof AdminMemorialsNewRoute
  '/settings/custom-fields': typeof AdminSettingsCustomFieldsRoute
  '/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/m/$slug/claim': typeof MSlugClaimRoute
  '/contacts': typeof AdminContactsIndexRoute
  '/memorials': typeof AdminMemorialsIndexRoute
  '/settings': typeof AdminSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/m/$slug': typeof MSlugRouteWithChildren
  '/m/': typeof MIndexRoute
  '/_admin/memorials/categories': typeof AdminMemorialsCategoriesRoute
  '/_admin/memorials/new': typeof AdminMemorialsNewRoute
  '/_admin/settings/custom-fields': typeof AdminSettingsCustomFieldsRoute
  '/_admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/m/$slug/claim': typeof MSlugClaimRoute
  '/_admin/contacts/': typeof AdminContactsIndexRoute
  '/_admin/memorials/': typeof AdminMemorialsIndexRoute
  '/_admin/settings/': typeof AdminSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/m/$slug'
    | '/m/'
    | '/memorials/categories'
    | '/memorials/new'
    | '/settings/custom-fields'
    | '/settings/notifications'
    | '/m/$slug/claim'
    | '/contacts/'
    | '/memorials/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/m/$slug'
    | '/m'
    | '/memorials/categories'
    | '/memorials/new'
    | '/settings/custom-fields'
    | '/settings/notifications'
    | '/m/$slug/claim'
    | '/contacts'
    | '/memorials'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/login'
    | '/_admin/dashboard'
    | '/m/$slug'
    | '/m/'
    | '/_admin/memorials/categories'
    | '/_admin/memorials/new'
    | '/_admin/settings/custom-fields'
    | '/_admin/settings/notifications'
    | '/m/$slug/claim'
    | '/_admin/contacts/'
    | '/_admin/memorials/'
    | '/_admin/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  MSlugRoute: typeof MSlugRouteWithChildren
  MIndexRoute: typeof MIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/': {
      id: '/m/'
      path: '/m'
      fullPath: '/m/'
      preLoaderRoute: typeof MIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$slug': {
      id: '/m/$slug'
      path: '/m/$slug'
      fullPath: '/m/$slug'
      preLoaderRoute: typeof MSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings/': {
      id: '/_admin/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/memorials/': {
      id: '/_admin/memorials/'
      path: '/memorials'
      fullPath: '/memorials/'
      preLoaderRoute: typeof AdminMemorialsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/contacts/': {
      id: '/_admin/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AdminContactsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/m/$slug/claim': {
      id: '/m/$slug/claim'
      path: '/claim'
      fullPath: '/m/$slug/claim'
      preLoaderRoute: typeof MSlugClaimRouteImport
      parentRoute: typeof MSlugRoute
    }
    '/_admin/settings/notifications': {
      id: '/_admin/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AdminSettingsNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings/custom-fields': {
      id: '/_admin/settings/custom-fields'
      path: '/settings/custom-fields'
      fullPath: '/settings/custom-fields'
      preLoaderRoute: typeof AdminSettingsCustomFieldsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/memorials/new': {
      id: '/_admin/memorials/new'
      path: '/memorials/new'
      fullPath: '/memorials/new'
      preLoaderRoute: typeof AdminMemorialsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/memorials/categories': {
      id: '/_admin/memorials/categories'
      path: '/memorials/categories'
      fullPath: '/memorials/categories'
      preLoaderRoute: typeof AdminMemorialsCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminMemorialsCategoriesRoute: typeof AdminMemorialsCategoriesRoute
  AdminMemorialsNewRoute: typeof AdminMemorialsNewRoute
  AdminSettingsCustomFieldsRoute: typeof AdminSettingsCustomFieldsRoute
  AdminSettingsNotificationsRoute: typeof AdminSettingsNotificationsRoute
  AdminContactsIndexRoute: typeof AdminContactsIndexRoute
  AdminMemorialsIndexRoute: typeof AdminMemorialsIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminMemorialsCategoriesRoute: AdminMemorialsCategoriesRoute,
  AdminMemorialsNewRoute: AdminMemorialsNewRoute,
  AdminSettingsCustomFieldsRoute: AdminSettingsCustomFieldsRoute,
  AdminSettingsNotificationsRoute: AdminSettingsNotificationsRoute,
  AdminContactsIndexRoute: AdminContactsIndexRoute,
  AdminMemorialsIndexRoute: AdminMemorialsIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MSlugRouteChildren {
  MSlugClaimRoute: typeof MSlugClaimRoute
}

const MSlugRouteChildren: MSlugRouteChildren = {
  MSlugClaimRoute: MSlugClaimRoute,
}

const MSlugRouteWithChildren = MSlugRoute._addFileChildren(MSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  MSlugRoute: MSlugRouteWithChildren,
  MIndexRoute: MIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
